config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :home, only: [:index, :secret]
  resources :event do
  	resources :charges
	end
  resources :users, only: [:show, :edit, :update]
  resources :participations, only: [:index, :new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  #after_create :new_attendee_send < Email send off because he fuck up heroku >

  belongs_to :user
  belongs_to :event

  private
  
  def new_attendee_send
    AttendanceMailer.new_attendee_email(@self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :admin, class_name: "User"
  has_many  :attendances
  has_many :users, through:  :attendances

  
  validates :start_date, presence: true, if: :already_past

  validates :duration, presence: true, if: :validate_duration
  validates :title, presence: true, length: {minimum: 5, maximum: 140} 
  validates :description, presence: true, length: {minimum: 20, maximum: 1000}
  validates :price, presence: true, if: :validate_price
  validates :location, presence: true  

  private
  def validate_price
    if price >= 1 && price <= 1000
      return true
    else
      errors.add{"Price not good ! min 1 / max 1000"}
    end
  end

  def validate_duration
    if duration > 0 && duration % 5 == 0
      return true
    else 
      errors.add("duration not valid please retry")
    end
  end

  def already_past
    if start_date.to_date < DateTime.now
      errors.add{"Event already past"}
    end 
  
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable       
  #after_create :welcome_send  < Comment for dont fuckup with heroku >

  has_many :attendances
  has_many :events, through: :attendances
  has_many :created_events, class_name: "Event", foreign_key: "admin_id"

  private
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	before_action :admin_user, only: [:index, :edit]

	def index
    @attendances = []
    attendances_ids = Attendance.where(event_id: params[:event_id]).ids
    attendances_ids.each do |id|
    	@attendances << Attendance.find(id)
    end
	end	

	def new
  	@event = Event.find(params[:event_id])
  	@amount = @event.price
	end

	def create
		@event = Event.find(params[:event_id])
  	@amount = @event.price

  	customer = Stripe::Customer.create(
    	:email => params[:stripeEmail],
    	:source  => params[:stripeToken]
		)
		
  	charge = Stripe::Charge.create(
    	:customer    => customer.id,
    	:amount      => @amount,
    	:description => 'Rails Stripe customer',
    	:currency    => 'eur'
		)

		a = Attendance.new(stripe_customer_id: customer.id, event_id: @event.id, user_id: current_user.id)

		if a.save
			redirect_to event_path(@event.id)
		else
			render new_event_charge_path(@event.id)
		end

	rescue Stripe::CardError => e
  	flash[:error] = e.message
  	redirect_to new_charge_path
	
	end

	private
	
	def admin_user
    @event = Event.find(params[:event_id])
    unless @event.admin_id == current_user.id
      flash[:danger] = "It is not your event"
      redirect_to event_index_path
      return true
    end
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.create!(title: params[:title],description: params[:description], start_date: params[:start_date], duration: params[:duration], price: params[:price], location: params[:location], admin_id: current_user.id)
    if @event.save
      flash[:success] = "Event created!"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(title: params[:title],description: params[:description], start_date: params[:start_date], duration: params[:duration], price: params[:price], location: params[:location])
      flash[:success] = "Event Update!"
      redirect_to event_path(@event.id)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to event_index_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def index
  	
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :own_profile, only: [:show]
  
  def show
  end

  def update
    @user = User.find(params[:id])
    if @user.update(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], description: params[:description])
      flash[:success] = "Profile Update!"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def own_profile
    if params[:id].to_i == current_user.id
    else
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper

  def new_event
    Event.new
  end

  def current_event
    Event.find(@event.id)
  end

  def event_end_date
    event_end_at = @event.start_date + @event.duration.minutes
  end

  def admin_event_email
    User.find(current_event.admin_id).email
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%=@amount%> €</strong>!</h2>

app/views/charges/index.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 class="my-3">Here are all the attendees for your event "<%=@event.title%>"</h2>
          <%Attendance.all.each do |participation|%>
            <ul class="ml-4 list-unstyled">
              <%if participation.event_id == @event.id%>
                <li>🙋 <%=User.find_by(id: participation.user_id).first_name%></li>
              <%end%>
              </ul>
          <%end%>
          <br>
          <div class="row mt-2">
            <%= link_to "Edit", edit_event_path(@event.id), class: "btn btn-info ml-4", :method => 'get'%>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/charges/intex.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <p>Bonjour</p>
  </body>
</html>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%=@amount %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%=@amount*100%>"
          data-locale="auto"></script>
<% end %>

app/views/event/edit.html.erb
<div class="container" >
  	<div class="row">
  		<div class="col-md-8 mx-auto mt-5">

      	<%= form_tag url_for(action: "update"), method: "put" do |f| %>
        <%= label_tag 'Start_Date' %>
        <%= text_field_tag 'start_date', @event.start_date, class: 'form-control'%>
        <%= label_tag 'Duration' %>
        <%= text_field_tag 'duration', @event.duration, class: 'form-control'%>
        <%= label_tag 'Location' %>
        <%= text_field_tag 'location', @event.location, class: 'form-control'%>
        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', @event.title, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', @event.description, class: 'form-control'%>
        <%= label_tag 'Price' %>
        <%= text_field_tag 'price', @event.price, class: 'form-control'%>
        <br/>
        <%= submit_tag "Modify event", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

  		</div>
  	</div>
  </div>  

app/views/event/index.html.erb
<div class="container">
  <div class="row flex-row">
    <div class="col d-flex justify-content-center mt-3">
      <h2>Here are all the events :</h2>
    </div>
  </div>
  
  <div class="row">
    <%Event.all.each do |event|%>
      <%@event = event %>
      <div class="text-center col-md-4 mb-5 my-5">
        <h3><%= event.title.capitalize!%></h3>
        <h4 class="text-center card-subtitle mb-2 text-muted">by <%= User.find(@event.admin_id).first_name%> </h4>
        <p class="text-center card-text"><%= @event.description[0..80] %>...</p> 
        <p><a href="<%= event_path(@event.id)%>" class="btn btn-info">Voir l'event</a></p>
      </div>
    <%end%>
  </div>
</div>

app/views/event/new.html.erb
<div class="container" >
    <div class="row">
      <div class="col-md-8 mx-auto mt-5">

        <%= form_tag url_for(action: "create"), method: "post" do |f| %>
        <%= label_tag 'Start_Date' %>
        <%= text_field_tag 'start_date', new_event.start_date, class: 'form-control'%>
        <%= label_tag 'Duration' %>
        <%= text_field_tag 'duration', new_event.duration, class: 'form-control'%>
        <%= label_tag 'Location' %>
        <%= text_field_tag 'location', new_event.location, class: 'form-control'%>
        <%= label_tag 'Title' %>
        <%= text_field_tag 'title', new_event.title, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', new_event.description, class: 'form-control'%>
        <%= label_tag 'Price' %>
        <%= text_field_tag 'price', new_event.price, class: 'form-control'%>
        <br/>
        <%= submit_tag "Create event", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

      </div>
    </div>
  </div>  

app/views/event/show.html.erb
<div class="container show_event">
  <div class="col text-center">
    <h2>Event n°<%=@event.id%></h2><br>
  </div>

  <div class="card mx-3">
    <div class="card-header">
      <strong><%= @event.title%></strong>
    </div>

    <div class="card-body px-4">

      <br/>   
      <p><strong>Price :</strong> <%= @event.price%></p>
      <p><strong>Duration:</strong><%= @event.duration%> min</p>
      <p><strong>Participation :</strong> <%= Attendance.where(event_id: @event.id).count  %></p>
      <p><strong>Administrator mail :</strong> <%= User.find(@event.admin_id).email %></p>
      <p><strong>Start at :</strong> <%= @event.start_date%></p>
      <p><strong>End at :</strong> <%=event_end_date%></p>
      <p><strong>Location :</strong> <%= @event.location%></p>
      <blockquote class="blockquote mb-0">
        <em>"<%= @event.description %>"</em><p></p>
        <footer class="blockquote-footer">
          <p><strong>By :</strong><%= User.find(@event.admin_id).first_name%> <%= User.find(@event.admin_id).last_name %></a></p>
          <p>Create: <%= @event.created_at %></p>

          <div class="row flex-row">
            <%if current_user%>
              <%if current_user.id == @event.admin_id%>
                <a href="<%=edit_event_path(@event.id)%>" class="btn btn-info ml-4">Edit event</a>
                <%= form_tag url_for(action: 'destroy'), method: "delete" do%>
                  <%= submit_tag "Delete event", class: 'btn btn-danger ml-3'%>
                <%end%>
              <%end%>
              <%else%>
                <span class="d-flex align-items-center">Login to edit your event</span>
           <%end%>

            <%if current_user && @event.admin_id == current_user.id %>
              <%= link_to "Who's already check-in", event_charges_path(@event.id), :method => 'get', class: 'btn btn-success ml-3'%>
            <%end%>
            <br>
            <%if current_user && @event.admin_id != current_user.id%> 
              <%= link_to "Participe !", new_event_charge_path(@event.id), :method => 'get', class: 'btn btn-success ml-3'%>
            <%elsif current_user && @event.admin_id == current_user.id %>
              <span class="d-flex align-items-center ml-3">You'r the administrator you can't participate</span>
            <%elsif current_user && Attendance.where(user_id: current_user.id).exists?%>
              <span class="d-flex align-items-center ml-3">You'r already participate</span>
            <%else %>
              <%= link_to "Participe !", new_user_session_path, :method => 'get', class: 'btn btn-success ml-3'%>
            <%end%>
          </div>

        </footer>
      </blockquote>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron bg-dark ">
        <div class="container">
          <h1 class="text-center text-white display-3 mb-5">Welcome on The Event Project</h1>
          <div class="text-center text-white col-md-8 mx-auto mb-5">This website gather all the events organized in Montpellier and around. Sign up now and enter in the events creators community!</div>
          <div class="text-center col-md-8 mx-auto mb-5"><a class="btn btn-primary btn-lg" href="<%=new_event_path%>" role="button">Create an event &raquo;</a></div>
        </div>
      </div>

      <div class="container">
        <div class="row">
        	<%Event.all.each do |event|%>
        	<%@event = event %>
          <div class="text-center col-md-4 mb-5 my-5">
            <h2><%= event.title.capitalize!%></h2>
            <h3 class="text-center card-subtitle mb-2 text-muted">by <%= User.find_by(id: event.admin_id).first_name%> </h3>
            <p class="text-center card-text"><%= @event.description[0..200] %>...</p> 
            <p><a href="<%= event_path(@event.id)%>" class="btn btn-info">Voir l'event</a></p>
          </div>
          <%end%>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


  </head>

  <body>
  
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%=root_path%>">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Create event", new_event_path, :method => 'get', class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Our amazing events !", event_index_path, :method => 'get', class: "nav-link"%>
          </li>          
          
          <%if current_user%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "My profile", user_path(current_user.id), :method => 'get', class: "dropdown-item"%>
                <%= link_to "Deconnect", destroy_user_session_path, :method => :delete, class: "dropdown-item"%>
              </div>
            </li>
          <%else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sign up/Log in
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Sign up", new_user_registration_path, :method => 'get', class: "dropdown-item"%>
              <%= link_to "Log in", new_user_session_path, :method => 'get', class: "dropdown-item"%>
              </div>
            </li>
          <%end%>
        </ul>
      </div>
    </nav>
  
    <%= yield %>

    <footer class="footer bg-dark">
      <div class="container text-center py-2">
        <p class="text-muted small"> ☀ All website is created by ☀ <a href="https://github.com/Rianasoa"> 🧙‍♀ Rianah Ounie</a> / <a href="https://github.com/RADONARINDRA"> 🧙‍♂️Rado Narindra</a> 
      </div>
    </footer>


  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


  


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


  </head>
  
  <body>

  	<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="<%=root_path%>">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Create event", new_event_path, :method => 'get', class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Our amazing events !", event_index_path, :method => 'get', class: "nav-link"%>
          </li>          
          
          <%if current_user%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "My profile", user_path(current_user.id), :method => 'get', class: "dropdown-item"%>
                <%= link_to "Deconnexion", destroy_user_session_path, :method => 'DELETE', class: "dropdown-item"%>
              </div>
            </li>
          <%else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sign up/Log in
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Sign up", new_user_registration_path, :method => 'get', class: "dropdown-item"%>
              <%= link_to "Log in", new_user_session_path, :method => 'get', class: "dropdown-item"%>
              </div>
            </li>
          <%end%>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/participations/create.html.erb
<h1>Participations#create</h1>
<p>Find me in app/views/participations/create.html.erb</p>

app/views/participations/destroy.html.erb
<h1>Participations#destroy</h1>
<p>Find me in app/views/participations/destroy.html.erb</p>

app/views/participations/index.html.erb
<h1>Participations#index</h1>

app/views/participations/new.html.erb
<h1>Participations#new</h1>


<form action="your-server-side-code" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_TYooMQauvdEDq54NiTphI7jx"
    data-amount="999"
    data-name="Stripe.com"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true">
  </script>
</form>

app/views/users/edit.html.erb
<div class="container" >
  	<div class="row">
  		<div class="col-md-8 mx-auto mt-5">

      	<%= form_tag url_for(action: "update"), method: "put" do |f| %>
        <%= label_tag 'First name' %>
        <%= text_field_tag 'first_name', current_user.first_name, class: 'form-control'%>
        <%= label_tag 'Last name' %>
        <%= text_field_tag 'last_name', current_user.last_name, class: 'form-control'%>
        <%= label_tag 'Description' %>
        <%= text_field_tag 'description', current_user.last_name, class: 'form-control'%>
        <%= label_tag 'email' %>
        <%= text_field_tag 'email', current_user.email, class: 'form-control'%>
        <br/>
        <%= submit_tag "Modify profil", class: 'btn btn-lg btn-primary btn-block' %>

      <% end %>

  		</div>
  	</div>
  </div>  

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1 class="my-3"><%=current_user.first_name%>'s profile page</h1>
    </div>
  </div>

  <div class="row flex-row">
    <div class="col">
      <h2>My informations</h2>
      <ul>
        <li><%=current_user.first_name%> <%=current_user.last_name%></li><br>
        <li><%=current_user.description%></li><br>
        <li><%=current_user.email%></li>
      </ul>
      <br><br>
      <h2>My events</h2>
        <div class="row">
        <% Event.all.each do |event|%>
          <%@event = event%>
          <%if event.admin_id == current_user.id%>
          <div class="text-center col-md-4 mb-5 my-5">
            <h2><%= event.title.capitalize!%></h2>
            <h3 class="text-center card-subtitle mb-2 text-muted">by <%= User.find_by(id: event.admin_id).first_name%> </h3>
            <p class="text-center card-text"><%= @event.description[0..80] %>...</p> 
            <p><%= link_to "See the event", event_path(@event.id), :method => 'get', class: "btn btn-info"%></p>
          </div>
          <%end%>
        <%end%>
      </div>
      <br><%= link_to "Edit my informations", edit_user_path(current_user), :method => 'get', class: "btn btn-info d-flex justify-content-end"%><br><br>
    </div>
  </div>
</div>